# Generated by Django 3.2.12 on 2022-03-20 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_auto_20220319_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='_cache_qtde',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Qtde de casas'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Data'),
        ),
    ]
