# Generated by Django 3.2.12 on 2022-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_orcamento_casas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='casas',
            field=models.ManyToManyField(editable=False, to='imoveis.Casa', verbose_name='Casas'),
        ),
    ]
