# Generated by Django 3.2.12 on 2022-03-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_alter_orcamento_casas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='_cache_qtde',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='investimento_total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Total do Investimento'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_remanescente',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Valor Remanescente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor para Investimento'),
        ),
    ]
