# Generated by Django 3.2.12 on 2022-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
        ),
    ]
